### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by jessicard** [seatgeek/react-infinite#10]
When implementing react-infinite for trs on a table, I get some issues. Is it possible to use react-infinite for tables?

My markup is approximately set up like this:
```js
<table>
  <tbody>
    <Infinite
      onInfiniteLoad={@paginateErrors}
      loadingSpinnerDelegate={@elementInfiniteLoad()}
      isInfiniteLoading={@state.errors.paginating}
      elementHeight={40}
      containerHeight={250}
      infiniteLoadBeginBottomOffset={200}>

      {@state.errors.map (error) =>
        <tr>
          <td>
            <div>
              <input type="checkbox" onChange={@onChange} checked={@isSelected()} />
              {@props.error.status} - {@props.error.id}
            </div>
          </td>
        </tr>
      }

    </Infinite>
  </tbody>
</table>
```

I get the error message:
"Uncaught Error: Invariant Violation: findComponentRoot(..., .rp2kounw1s.1.1.0.1.0.0.0.0.1:$54d55d0f6377e4eee752eada.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a \<tbody> when using tables, nesting tags like \<form>, \<p>, or \<a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ."

It's very possible I'm going about this in the wrong way - thoughts?

**Comment by garetht** [comment]
Since `react-infinite` wraps its content in two nested `div`s, the generated HTML would be invalid. Chrome, at least, seems to respond by deleting the `div`s, which I believe causes the error.

The CSS spec seems to only define overflow on block boxes (i.e. a `tbody` is not by default scrollable), so adding features to `react-infinite` to override the table model layout is not something I think is the best option. I would follow the HTML structure of the examples.

**Comment by jessicard** [comment]
Ahh, that makes total sense. Thanks so much for your feedback @garetht!
