### ISSUE TITLE
Knowing current element in focus.

### ISSUE THREAD

**Issue by Oted** [seatgeek/react-infinite#111]
Hi, I have been playing around with react-infinite for a while and i think it works great. However, i don't know there is any feature to know what element currently is in the middle of the view. If there isnt, i think that would be an awesome feature to add. I am currently using this code snipet but it's not very smooth. 

```
    ...
    handleScroll={function(node) {
        var targets = node.children[0].children,
            target  = targets[Math.floor(targets.length / 2) - 1];
       
        Action.itemInFocus(target);
    }},
    ...
```

Any feedback on the code above would be great, maybe im missing something vital here.

**Comment by garetht** [comment]
I think it is unlikely for the code presented above to be smooth because non-trivial computations appear to be carried out with `Action.itemInFocus`, which would called on every scroll. The correct solution would call `Action.itemInFocus` at greater intervals, depending on your use case, but certainly not on every scroll action. I don't think there are any plans to expose which element is currently in the middle, but I'll reopen this if that changes.
