### ISSUE TITLE
Jerky scrolling

### ISSUE THREAD

**Issue by harrybabu** [seatgeek/react-infinite#139]
Hi,

I am having a react-infinite component like this one, 

`<Infinte
            containerHeight={900}
            elementHeight={310}
            infiniteLoadBeginEdgeOffset={400}
            handleScroll={this.handleInfiniteLoad}
            useWindowAsScrollContainer>
            {list}
          </Infinite>`

I am getting jerkiness while scrolling and the scrolling is not smooth.

Is there a way to debug this issue, to find what is causing the jerkiness?

**Comment by jcs12311** [comment]
I have a scroll problem, because the container has `overflow-y: scroll;`, the element that create by  `elementInfiniteLoad` was hide on the container, it need scroll to show.
I don't know how to solve this problem.

**Comment by erwaller** [comment]
Jerkiness while scrolling is generally caused by poor performance while rendering your components as they enter the view. Long renders will effectively cause the list to be drawn in the wrong place (ie. the list will have moved past where it was when the render was initiated) and then suddenly corrected, which will appear as a jerk.

The best way we've found to debug this is to use the chrome dev tools timeline to look for render functions that take a long time as you scroll the list around.

**Comment by harrybabu** [comment]
@erwaller exactly, this is the same issue i am having. How to fix it?

**Comment by erwaller** [comment]
Unfortunately, there's no simple fix. You just have to make sure the rendering of your components is as fast as possible.
