### ISSUE TITLE
How to print infinite list?

### ISSUE THREAD

**Issue by PavelVanecek** [seatgeek/react-infinite#149]
Hi,

we're struggling with print styles. Currently, react-infinite list prints many empty pages and then few items somewhere. We would like to print the whole list. It may be potentially infinite and [take a while](https://what-if.xkcd.com/59/) to print but this is left as decision to the user.

Is it possible to achieve this using only CSS print styles?

So far we have only figured out to include both react-infinite and hidden classic list on the page and swap them in print styles. That however defeats the purpose of having the infinite list in the first place.

**Comment by garetht** [comment]
It isn't possible with just CSS because the items are simply not present in the DOM. You can alter the [preload batch size](https://github.com/seatgeek/react-infinite#number--object-preloadbatchsize) and the preload additional height to make React Infinite render all the items in the list. This should allow all items to be printed.
