### ISSUE TITLE
How to develop using examples

### ISSUE THREAD

**Issue by garrettmaring** [seatgeek/react-infinite#206]
How to use the example pages for development. When you run `gulp develop` and then navigate to the .html files there are errors loading react.

**Comment by garetht** [comment]
React is loaded from `../node_modules/react/dist/react.js`. You may have to `npm install` first.

**Comment by chrisvoll** [comment]
@garetht Looks like the dist version of `react-infinite` includes a couple places where React is required without a global fallback:

```javascript
// good
var React = global.React || require('react');

// bad
var React = require('react');
```

Any thoughts on introducing browserify-shim or packaging the examples with modules?

**Comment by garetht** [comment]
In Javascript an error will be thrown only if the line in question is executed. This is not the case in the examples because we source `create-react-class` from elsewhere and the packaged version is unused.

In any case, the line will be going away very shortly in the next release and a further refactor of the asset pipeline will be in the works.
