### ISSUE TITLE
Migrate from React.createClass to JavaScript classes

### ISSUE THREAD

**Issue by domszyn** [seatgeek/react-infinite#216]
Usage of React.createClass has been deprecated in React 15.5.0

https://facebook.github.io/react/blog/#migrating-from-react.createclass

**Comment by Sharlaan** [comment]
React-infinite does not compile anymore in all my projects...
> Cannot find module "create-react-class".

This is now a critical issue.

**Comment by garetht** [comment]
You can pin your dependency to 0.10.0.

**Comment by amjacobowitz** [comment]
@Sharlaan If it is any help to you, I was able to patch over the issue by doing the following:

Add the module to your project:
`npm install create-react-class`

Then, in the offending component add:
`require('create-react-class');`

While this should fix the issue, I believe the real problem is with an upgrade to the React version involving a switch to es6.  I might be off on that though.

**Comment by garetht** [comment]
0.11 has a fix for this deprecation. An upgrade to ES2015 classes should come with 0.12.

**Comment by garetht** [comment]
0.12 has been released.
