### ISSUE TITLE
Performance is poor on mobile devices

### ISSUE THREAD

**Issue by Polyrhythm** [seatgeek/react-infinite#36]
I have utilized this in the context of a series of `<img>` elements for a mobile app. While testing on desktop, this works excellently, but on my Samsung Galaxy SIII, the scrolling performance is not great - either on Chrome or Android browser. I can easily scroll faster than the container can keep up and have to wait a very long time for items to render. There's also some jitter. Are there plans to optimize the performance of this?

**Comment by disusered** [comment]
I'm also interested in seeing this happen. I became very frustrated at one point trying to get this to work well, then came across a podcast about React Native. One of the team members joked that the motivation for the framework was spending six months trying to get long lists to work well on the mobile web, and failing. The point is, this is a hard problem and might not be solvable given the current constraints. Hell, Flipboard ditched the DOM entirely and rendered their list on canvas.

That said, I did profile and test on devices. You can play with preload amount to get better performance on mobile since the main bottleneck is the paint operation but this causes GC jank. The best options will depend on the constraint of the devices you are targeting.

With newer Android devices you have Crosswalk or Chrome's WebView, it can use native scroll events and greatly improve performance. On iOS it depends on the context, WKWebView (Mobile Safari, iOS 8+) can use native scroll events but older devices or WebViews (ie, Cordova iOS apps) can't. Not only that, but GPU operations are delayed while scrolling is active, exacerbating the flicker.

I think these are tractable with time.

**Comment by roundrobin** [comment]
Thanks @disusered for sharing your insights, this is very helpful. Did your mobile tests involved images on the cell or just simple text cells?

Did you ended up finding a good solution for you problem? Can you recommend using react-infinite for project made for modern mobile browsers?

**Comment by disusered** [comment]
Some lists are text-only while some have images (icons) within the cell. In both cases performance suffers in my app. Despite that, it's better than other DOM alternatives and I'm not ready to commit to something using canvas like the Flipboard solution (react-canvas). I have not had time to revisit this unfortunately.

**Comment by roundrobin** [comment]
@disusered thanks again. I found react-infinite the best solution out there so far, especially because it supports flexible heights on cells. I tried iScroll+infinite scrolling as a non react solution and it didn't really work well. The scrolling on mobile is janky and the infinite scrolling interface is not very advanced. AirBnB's infinity.js has almost no demos and is not really maintained anymore.

**Comment by gabrielhpugliese** [comment]
Facing that issue too :(

**Comment by vgoklani** [comment]
How do you get smooth scrolling on mobile?

**Comment by dustingetz** [comment]
Related to https://github.com/seatgeek/react-infinite/issues/63 which will probably help or maybe outright resolve this issue.

**Comment by garetht** [comment]
I just released 0.5.1, which adds the ability to use the window as the scroll container. Mobile scrolling works surprisingly well in that mode, which might help some use cases, although smooth scrolling for arbitrary `div`s has yet to be resolved.

**Comment by garetht** [comment]
We used React Infinite recently in a refresh of our mobile site. As far as I can tell, the issues described stem from the browsers themselves, which, in some of the worse cases, refuse to send a scroll event until the inertia of the scroll has ended or the user lifts their finger from the screen. This is [covered in more detail in this blog post](https://www.tjvantoll.com/2012/08/19/onscroll-event-issues-on-mobile-browsers/). Trying to detect scroll through `requestAnimationFrame` and `setTimeout` both fail as well. If anyone has any ideas around this please feel free to comment, but I will be closing this issue for now.

**Comment by chauthai** [comment]
@garetht I'm getting the same problems in a Cordova app too. 
The problem with the onScroll events not firing in mobile browsers is fixed in recent versions of Chrome and Safari on Android 6.0.1 and iOS 9.2.1.
I've tested it using the onScroll event tester on the site.

**Comment by garetht** [comment]
What precisely is the problem you're getting?

**Comment by chauthai** [comment]
I'm getting jitters and slow loading elements, when I start scrolling really fast.
If you want I can upload a screen record of the error.

**Comment by garetht** [comment]
Perhaps your elements require more than a negligible amount of time to render? It's possible to increase the batch sizes to pre-render more elements at once. Does the problem occur if you try it with cells of plain text?

**Comment by bvaughn** [comment]
I'm currently working on this same issue in [react-virtualized](https://github.com/bvaughn/react-virtualized). I've tried several approaches but I haven't been able to get rid of the flicker around the edges when the user quickly scrolls a list with "heavy" item renderers.

> Perhaps your elements require more than a negligible amount of time to render? It's possible to increase the batch sizes to pre-render more elements at once. Does the problem occur if you try it with cells of plain text?

Enabling Chrome's "paint flashing" tool shows that _some_ of this is due to item cells that take a bit of time to render. But the repaint itself reveals that some of the empty space hasn't been repainted yet because the scroll event just hasn't caught up.

Pre-rendering more elements does help up to a degree but it can also reduce the frame rate and have a negative impact too, depending on the context.

Anyway, I don't have a solution to offer at this point but I wanted to hook into this thread so that we could potentially help each other. :)
