### ISSUE TITLE
Can't load more elements if the initial elements don't cause a scrollbar to appear

### ISSUE THREAD

**Issue by vith** [seatgeek/react-infinite#39]
Since `react-infinite` can only load more items in response to a scroll event, if there's not enough loaded at the start to enable scrolling the user is stuck.

For now I have a workaround like this on my wrapper:

```es6
    componentDidUpdate(prevProps: object, prevState: object) {
        let element = React.findDOMNode(this);

        if (this.state.initialLoad) {
            if (element.clientHeight === element.scrollHeight) {
                // didn't load enough to enable scrolling yet
                if (!this.state.isInfiniteLoading) {
                    console.log("loading more at initial");
                    this.handleInfiniteLoad();
                }
            } else {
                this.setState({
                    initialLoad: false
                });
            }
        }
    }
```

Can a similar check be done internally to the `<Infinite/>` component instead?

Let me know if you need a demo of this issue.

**Comment by jayfunk** [comment]
I believe this was fixed by my changes that were pulled in today. Pull down the latest and give it a try. I had a similar issue with it.

**Comment by garetht** [comment]
In an upcoming change, React Infinite will call `onInfiniteLoad` once on `componentDidMount` if the total height of the elements is less than the the height of the container.

The proposed change in this issue will not be made because there is no way that React Infinite can know what elements the parent component will return to it, creating the potential for an infinite loop.
