### ISSUE TITLE
Shows loading spinner even when isInfiniteLoading is set to false

### ISSUE THREAD

**Issue by mdesai-vixlet** [seatgeek/react-infinite#55]
When you reach to the end of the page, you see the spinner spinner element even when isInfiniteLoading is set to false. It does not go away until you manually trigger a prop change on the value passed in to the isInfiniteLoading prop.

<Infinite elementHeight={70}
                  containerHeight={containerHeight}
                  infiniteLoadBeginBottomOffset={5}
                  onInfiniteLoad={this.props.loadMoreLikers}
                  loadingSpinnerDelegate={this.elementInfiniteLoad()}
                  isInfiniteLoading={false}

The above code will show the spinner element when you scroll to the end of page.

**Comment by clayne11** [comment]
This is definitely a bug IMO. The docs state that "Before this function is called, the infinite loading spinner is automatically turned on" but this makes no sense to me.

When I have reached the end of my data a call to "onInfiniteLoad" will do nothing and should not show the spinner. But since I don't react to "onInfiniteLoad", since there is no more data to load. The spinner never goes away. I have managed to work around this issue by manually changing the loadingSpinnerDelegate to not have visibility but this is not the correct solution.

**Comment by garetht** [comment]
@mdesai-vixlet @clayne11 This is by design and is not a bug.

It seems quite clear that when `onInfiniteLoad` is called, the loading spinner of your choice should be turned on. The fact that `isInfiniteLoading` is now out of sync with the actual state of the component is based on the pattern in [this Flux example](https://github.com/facebook/flux/blob/master/examples/flux-todomvc/js/components/TodoTextInput.react.js) - the value `prop` of the text field is out of sync while the field is being edited, but upon save they are brought back in sync. If React Infinite relies only on the prop `isInfiniteLoading` to turn the spinner on, this may lead to an unacceptable period of waiting while the change filters through (in Flux or a more complex application, for example) the stores and all the way down from the parent component.

If you know that the current call of `onInfiniteLoad` is the last that will return any data, then you should turn off infinite loading. This can be done, [as the documentation describes](https://github.com/seatgeek/react-infinite#number-infiniteloadbeginbottomoffset), by setting `infiniteLoadBeginBottomOffset` to `undefined`. No further calls will then be made to `onInfiniteLoad`, and the spinner will never show.

If you want there to be infinite loading but never want to show the spinner, set the `loadingSpinnerDelegate` appropriately.

Let me know if there's anything more I can clarify.
