### ISSUE TITLE
performance optimization suggestion

### ISSUE THREAD

**Issue by stepancar** [seatgeek/react-infinite#98]
now we pass options for infinity scroll by children. lets consider situation: we want to pass 20000 items with hard logic in contructor and pass it to infinity scroll as children. in this case , as i undestand, we will created 20000 objects in memory, but only 20-30 will be rendered by infinity scroller. Maybe we can pass option throught props without creating react component instances. For each option just add calback which will return react component. 
now create 20000 react components -> filter by scroll position-> render 20
what i mean 20000 objects (not react components) -> filter by scroll-> render 20
thank you

**Comment by garetht** [comment]
@stepancar Thanks for the suggestion! The simplest way to use React Infinite would have 20 000 React components in memory. However, if you use the infinite scroll feature, you only need to create as many React components as you wish to display. You would pass 10 children into React Infinite at first, then after `onInfiniteScroll` is called, the parent can render 10 more React components and have 20 components in memory, until you get to 100 components in memory, 1000 components in memory, and so forth. This allows batching of the calls that cause component creation.

This leads to about the same memory usage as your suggestion, because I think a sensible implementation of your suggestion would require some sort of caching of the created React components  to prevent a waste of processor power if a user scrolls back and forth between different sections.

I think that there may be a case in which you suggestion might lead to decreased memory usage if coupled with a sensible cache eviction policy. If a user gets to the end of the 20 000 items, perhaps the first 5 000 items are no longer needed. But it is also possible to do this in the current system. Because the heights of the elements are all known, the first 5 000 elements can be replaced with a single placeholder `div` with the height of the evicted components, thus freeing them from memory. This might perhaps be less elegant, but achieves the same result.
